# Dependencies
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids:     true

permalink: pretty

# Server
source:         "site"
destination:    ./docs
host:           flo-scss.flo.center
port:           80
baseurl:        ""
url:            "https://flo-scss.flo.center"
encoding:       UTF-8
exclude:
  - docs/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title: Flo-SCSS
description: 'Based on The most popular HTML, CSS, and JS library in the world.'
twitter: flosports
authors: 'FloSports Engineering, Mark Otto, Jacob Thornton, and Bootstrap contributors'
social_image_path: /docs/assets/brand/bootstrap-social.png
social_logo_path: /docs/assets/brand/bootstrap-social-logo.png

# Custom Variables
current_version:      0.7.0
current_ruby_version: 0.7.0
docs_version:         0.7.0
github_org:           "https://github.com/flocasts"
repo:                 "https://github.com/flocasts/flo-scss"
slack:                "https://www.flosports.tv"
opencollective:       "https://www.flosports.tv"
blog:                 "https://www.flosports.tv"
expo:                 "https://www.flosports.tv"
themes:               "https://www.flosports.tv"
icons:                "https://flo-scss.flo.center"

download:
  source: "https://github.com/flocasts/flo-scss/archive/v0.7.0.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css: 'sha384-MMLzfhqcj7iAztos0doM4v4OXRfBzu1mFfFV+hNw/dvth+emrA3riw9Y+XCaMyFd'
  css_hash: sha384-hnvsmW4CEqIE9xpwdmvw+oyi2zalIdkqZJKT8ovyObj2fiPNSLt7xdsda4JGUfSf
  js: 'sha384-MMLzfhqcj7iAztos0doM4v4OXRfBzu1mFfFV+hNw/dvth+emrA3riw9Y+XCaMyFd'
  js_hash: sha384-1RkA5wjfeG5u+6ycZ90q+PMlafLBaMCHvGk6PlVrQmIuTvpdA9qupxwbnPf9QbHH
  js_bundle: >-
    https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js
  js_bundle_hash: sha384-gEp0IQktG6BLXHMpPT1pxMSC8EKUA159uPI9c/AmIhedq/EvAEfBroQ5tsSOS1/A
  jquery: 'sha384-MMLzfhqcj7iAztos0doM4v4OXRfBzu1mFfFV+hNw/dvth+emrA3riw9Y+XCaMyFd'
  jquery_hash: sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n
  popper: 'sha384-MMLzfhqcj7iAztos0doM4v4OXRfBzu1mFfFV+hNw/dvth+emrA3riw9Y+XCaMyFd'
  popper_hash: sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN

toc:
  min_level: 2
  max_level: 4
  no_toc_section_class:
    - bd-callout
    - bd-example
