current_version: 0.3.1
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
permalink: pretty
source: site
destination: ./docs
host: flo-scss.flo.center
port: 80
baseurl: ''
url: 'https://flo-scss.flo.center'
encoding: UTF-8
exclude:
  - docs/assets/scss/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
title: Flo-SCSS
description: 'Based on The most popular HTML, CSS, and JS library in the world.'
twitter: flosports
authors: 'FloSports Engineering, Mark Otto, Jacob Thornton, and Bootstrap contributors'
social_image_path: /docs/assets/brand/bootstrap-social.png
social_logo_path: /docs/assets/brand/bootstrap-social-logo.png
current_ruby_version: 0.0.1
repo: 'https://github.com/twbs/bootstrap'
slack: 'https://bootstrap-slack.herokuapp.com'
opencollective: 'https://opencollective.com/bootstrap'
blog: 'https://blog.getbootstrap.com'
expo: 'https://expo.getbootstrap.com'
themes: 'https://themes.getbootstrap.com'
icons: 'https://icons.getbootstrap.com'
download:
  source: 'https://github.com/twbs/bootstrap/archive/v4.4.1.zip'
  dist: >-
    https://github.com/twbs/bootstrap/releases/download/v4.4.1/bootstrap-4.4.1-dist.zip
cdn:
  css: 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'
  css_hash: sha384-hnvsmW4CEqIE9xpwdmvw+oyi2zalIdkqZJKT8ovyObj2fiPNSLt7xdsda4JGUfSf
  js: 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js'
  js_hash: sha384-1RkA5wjfeG5u+6ycZ90q+PMlafLBaMCHvGk6PlVrQmIuTvpdA9qupxwbnPf9QbHH
  js_bundle: >-
    https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js
  js_bundle_hash: sha384-gEp0IQktG6BLXHMpPT1pxMSC8EKUA159uPI9c/AmIhedq/EvAEfBroQ5tsSOS1/A
  jquery: 'https://code.jquery.com/jquery-3.4.1.slim.min.js'
  jquery_hash: sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n
  popper: 'https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js'
  popper_hash: sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN
toc:
  min_level: 2
  max_level: 4
  no_toc_section_class:
    - bd-callout
    - bd-example
