# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - cicd
        - master
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6-buster-node  # language image

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            # - "bf:16:25:b1:2a:ff:dc:ee:ec:53:b4:33:95:86:c5:23"
            - "2d:80:03:87:eb:a2:56:8a:bd:ae:bc:45:09:9f:cf:48"

      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: bundle install
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # copy build artifacts to v4-dist and docs to gh-pages
      # - run: echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run: git config --global user.email "engineering@flosports.tv"
      - run: git config --global user.name "FloSports Engineering"
      - run: cd .. && cp -rf repo bs-docs
      - run: cd ../bs-docs && git checkout . && git checkout gh-pages && git pull
      - run: mkdir ../gh-pages && cp -rf ../bs-docs/.git ../gh-pages
      - run: npm run release
      - run: cp -rf docs/* ../gh-pages
      # - run: bash build/ship.sh 0.0.3
      - run: cd ../gh-pages && git add . && git commit -m 'CircleCI auto commit' && git push
      # - run: git checkout v4-dist
      # - run: git pull && git merge $CIRCLE_BRANCH --no-edit
      # - run: git add . && git commit -m 'CircleCI auto commit' && git push
