# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - circleci
        - master
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6-buster-node  # language image

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:58:a2:6e:11:ed:10:15:40:e5:5e:cc:cd:17:13:5a"

      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: bundle install
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # copy build artifacts to v4-dist and docs to gh-pages
      - run: echo "good morning"
      - run: echo "good morning"
      - run: git config --global user.email "engineering@flosports.tv"
      - run: git config --global user.name "FloSports Engineering"
      - run: cd .. && cp -rf repo bs-docs
      - run: cd ../bs-docs && git checkout . && git checkout gh-pages
      - run: bash build/ship.sh 4.4.1
      - run: cd ../bs-docs && git add . && git commit -m 'CircleCI auto commit' && git push
      - run: git checkout v4-dist
      - run: git pull && git merge $CIRCLE_BRANCH --no-edit
      - run: npm run release
      - run: git add . && git commit -m 'CircleCI auto commit' && git push
