# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  validate:
    docker:
      - image: circleci/node:lts
    working_directory: ~/flo-scss
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: lint
          command: npx commitlint --from=HEAD~1
  build:
    docker:
      - image: circleci/ruby:2.6-buster-node  # language image
    working_directory: ~/flo-scss
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: create build
          command: |
            cd .. 
            cp -rf flo-scss bs-docs
            cd bs-docs
            git checkout .
            git checkout gh-pages
            git pull
            cd ..
            mkdir gh-pages
            cp -rf bs-docs/.git gh-pages
            cp -rf flo-scss/.circleci gh-pages
            cd flo-scss
            npm run release
            cp -rf docs/* ../gh-pages

  release:
    docker:
      - image: circleci/ruby:2.6-buster-node  # language image

    working_directory: ~/flo-scss

    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:58:a2:6e:11:ed:10:15:40:e5:5e:cc:cd:17:13:5a"
      - run:
          name: setup git && npm
          command: |
            git config --global user.email "engineering@flosports.tv"
            git config --global user.name "FloSports Engineering"
            echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/flo-scss/.npmrc
      - run: 
          name: increment version
          command: echo 'standard-version'
      - run: 
          name: release github pages
          command: |
            cd ../gh-pages
            git add .
            git commit -m 'CircleCI auto commit'
            git push
      - run:
          name: release npm
          command: npm publish --access public

workflows:
  version: 2
  validate-build-release:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only: 
                - master
                - cicd
      - release:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
